# Generated by Django 2.2 on 2020-02-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('room_id', 'start_time', 'end_time')},
        ),
    ]
