# Generated by Django 2.2 on 2020-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single_Room', 'Single Room'), ('Family_Room', 'Family Room'), ('Delux_Suite', 'Delux Suite')], default='Single_Room', max_length=100),
        ),
    ]
