# Generated by Django 2.2 on 2020-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200227_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Family Room', 'Family Room'), ('Single Room', 'Single Room'), ('Delux Suite', 'Delux Suite')], default='Single Room', max_length=100),
        ),
    ]
