# Generated by Django 2.2 on 2020-03-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200227_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Family Room', 'Family Room'), ('Delux Suite', 'Delux Suite'), ('Single Room', 'Single Room')], default='Single Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rooms.Room'),
        ),
    ]
