# Generated by Django 2.2 on 2020-03-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200306_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Family Room', 'Family Room'), ('Delux Suite', 'Delux Suite')], default='Single Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='roombooked',
            name='customer_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerBooked', to='rooms.Customer'),
        ),
        migrations.AlterField(
            model_name='roombooked',
            name='room_timeslot_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslotBooked', to='rooms.TimeSlot'),
        ),
    ]
